### ISSUE TITLE
AnisotropicFilter option doesn't do anything

### ISSUE THREAD

**Issue by XJDHDR** [Alenett/TES-Reloaded-Source-NEW#2]
I have just noticed that the option to apply Anisotropic Filtering to the game doesn't actually do anything. 

Here is a screenshot of what I see when AnisotropicFilter = 0
![Elder Scrolls IV  Oblivion Screenshot 2020 05 21 - 19 39 41 34](https://user-images.githubusercontent.com/7355441/82536678-eeb0f780-9b9c-11ea-9547-1fb625e8eef7.png)

This is a screenshot of the same scene after I set AnisotropicFilter = 16
![Elder Scrolls IV  Oblivion Screenshot 2020 05 21 - 19 43 11 51](https://user-images.githubusercontent.com/7355441/82536904-4e0f0780-9b9d-11ea-8293-f9f8d11eab1f.png)

Finally, as a comparison, this is what the scene looks like when I force 16x AF through the Nvidia drivers:
![Elder Scrolls IV  Oblivion Screenshot 2020 05 21 - 19 49 32 23](https://user-images.githubusercontent.com/7355441/82536979-697a1280-9b9d-11ea-858e-632afb37c43a.png)

If it helps, here are some of my PC's specs:

- OS: Windows 10 x64 1909 (build 18363.836)
- GPU: Nvidia GeForce 1080 Ti
- Driver version: 445.75

**Comment by Alenett** [comment]
It works for me without problems. Be sure to set "leave the application to decide" in your video card settings.

**Comment by XJDHDR** [comment]
Well, it's not working for me. I already had that video card setting set to "application controlled". I wouldn't have filed this report in the first place if I had forced any AF option in the control panel. That also wouldn't have caused this problem in the first place. If I had mistakenly forced some value of AF in Nvidia's drivers, all three screenshots would have looked like the third. The first two showing no AF would have been impossible.
